# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

platform :ios do
  lane :example do
    souyuz(
      platform: "ios",
      build_configuration: "Release",
      plist_path: "/Users/susingh/Documents/Projects/TestProjectJenkins/TestFastlane25April/TestFastlane25April.iOS/Info.plist",
)
   testfairy(
  api_key: "9d738ee04953c0216d70c7d107b2a3b651f9d37c",
  ipa: "/Users/susingh/.jenkins/workspace/JenkinsFastlaneSetUp25April/TestFastlane25April.iOS/bin/iPhone/Release/TestFastlane25April.iOS.ipa",
)
  end
end
platform :android do
  lane :example do
    souyuz(
      platform: "android",
      build_configuration: "Release",
      keystore_path: "/Users/susingh/Library/Developer/Xamarin/Keystore/AndroidDemoCert/AndroidDemoCert.keystore",
      keystore_alias: "androiddemocert",
      keystore_password: "123456"
    )
    testfairy(
  api_key: "9d738ee04953c0216d70c7d107b2a3b651f9d37c",
  apk: "/Users/susingh/.jenkins/workspace/JenkinsFastlaneSetUp25April/TestFastlane25April.Android/bin/Release/com.companyname.testfastlane25april-Signed.apk",
 )
  end
end